version: "3.9"

services:
  server:
      build:
        context: .
        dockerfile: server.Dockerfile
      ports:
        - "5000:5000"
      links:
        - db
  model:
    build:
      context: .
      dockerfile: model.Dockerfile
    links:
      - db
  db:
      image: redis:alpine
      hostname: redis_host